# Generated by Django 5.1.6 on 2025-03-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
